default: &default
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  adapter: mysql2
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: twitter_feeds_development
